version: "3.9"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./media:/app/media
      - ./stream_config.db:/app/stream_config.db
    env_file:
      - .env
    environment:
      MEDIA_DIRECTORY: /app/media
    restart: unless-stopped
